### ISSUE TITLE
"Forward as Attachment" does not work

### ISSUE THREAD

**Issue by Bables55** [the-djmaze/snappymail#542]
**Describe the bug**
When I forward an existing email as an attachment, the recipient doesn't get it attached.
It is not attached to the sender's sent email either.

**To Reproduce**
1. Open mail.
2. Select "Forward as Attachment" from the hamburger menu.
3. Complete the body of the email.
4. Send an email.
5. The recipient receives the e-mail.

**Expected behavior**
The recipient will receive the email attached by the sender.

**Please complete the following information:**
- IMAP daemon: Postfix, dovecot
- PHP version: 8.1
- SnappyMail Version: 2.18.3

**Comment by ivnmad** [comment]
I can confirm the issue.
As soon as you select "Forward as Attachment" a new email is created, but there is no attachment.

**Comment by phsc84** [comment]
Yes, can confirm this as well. I guess it is related to #541.

The browser console shows the following error:
app.min.js:1 Uncaught TypeError: this.isPlainEditor is not a function
    at app.min.js:1:129841
    at ComposePopupView.editor (app.min.js:1:126264)
    at ComposePopupView.initOnShow (app.min.js:1:129804)
    at ComposePopupView.onShow (app.min.js:1:127276)
    at ki (app.min.js:1:80898)
    at AppUser.showMessageComposer (app.min.js:1:185531)
    at _s (app.min.js:1:58894)
    at MailMessageView.replyOrforward (app.min.js:1:157971)
    at app.min.js:1:154963
    at MailMessageView.s [as forwardAsAttachmentCommand] (app.min.js:1:154906)

A fix has already been committed: https://github.com/the-djmaze/snappymail/commit/8ca651b2fa227775c070406f6ad20380ac53f69d

**Comment by the-djmaze** [comment]
Solved with https://github.com/the-djmaze/snappymail/releases/tag/v2.18.4 ?

**Comment by ivnmad** [comment]
Just tested, and everything seems to be working fine with v2.18.4
