### ISSUE TITLE
TypeError:57.parentNode?.closest is not a function

### ISSUE THREAD

**Issue by stef157** [the-djmaze/snappymail#546]
**Describe the bug**
When I pick an email (with HTML) and try to edit and send it to someone, I get an error : TypeError:57.parentNode?.closest is not a function

**To Reproduce**
1. Go to INBOX (or other folder)
2. Click on an email
3. Click on the burger menu
4. Click on "edit as new"
5. Try so send
6. See the error

**Expected behavior**
The email should simply send

**Screenshots**

**Please complete the following information:**
- Browser:Firefox 105 / Safari 16 / Chrome 106
- IMAP daemon: dovecot
- PHP version: 8.0.24
- SnappyMail Version: 2.18.5 (work on 2.17.2)

<img width="1037" alt="Screenshoot 10-10-2022 at 14 50 07@2x" src="https://user-images.githubusercontent.com/1698095/194870964-f53fb9b7-dffa-440c-b88e-48d352054af8.png">

**Comment by the-djmaze** [comment]
This bug is similar to #516 and #524
So apparently there were multiple targets with this issue.
