### ISSUE TITLE
update to 2.17.3 has completely broken Reply All

### ISSUE THREAD

**Issue by jdaviescoates** [the-djmaze/snappymail#506]
**Describe the bug**
Reply All is currently Reply None

**To Reproduce**
1. Go to a message within Snappymail
2. Click on the menu hamburger top right
3. Hit Reply All
4. Note that zero email addresses are in the To field

**Expected behavior**
When I hit Reply All I expect all the emails from the email I'm replying in to be in the To and/ or cc fields.

**Please complete the following information:**
- Browser: firefox 104
- IMAP daemon: dovecot
- PHP version: not sure
- SnappyMail Version: 2.17.3

**Additional context**
This is on SnappyMail installed using Cloudron

**Comment by codiflow** [comment]
Totally confirm that.

I have a clean installed version without Cloudron and the issue is the same.

First thought it has something to do with the new "default settings" but changing some of them didn't change anything in behaviour.

The new window is completely empty – its not just not filling in the recipients, its also not filling in the Reply subject and the signature / email you are replying to:
![image](https://user-images.githubusercontent.com/43847817/187475218-268cb68a-a59f-40d8-9d6e-86cb4f7d66c2.png)


I also noticed (might be another issue) that the sender of an email is not clickable anymore after updating to 2.17.3:
![image](https://user-images.githubusercontent.com/43847817/187475077-4c1f10b9-b02a-4612-8e79-486fcd7702a2.png)

**Comment by jdaviescoates** [comment]
I'm guessing perhaps fixing replying to messages in sent items #497 might've somehow effected this?

**Comment by the-djmaze** [comment]
> I'm guessing perhaps fixing replying to messages in sent items #497 might've somehow effected this?

Correct #497 changes caused the issue

**Comment by codiflow** [comment]
I'm getting the following error in the browsers console:

```
17:41:01.029 Uncaught TypeError: e.map is not a function
    vr https://mail.mydomain.de/snappymail/v/2.17.3/static/js/min/app.min.js:1
    initOnShow https://mail.mydomain.de/snappymail/v/2.17.3/static/js/min/app.min.js:1
    onShow https://mail.mydomain.de/snappymail/v/2.17.3/static/js/min/app.min.js:1
    Ei https://mail.mydomain.de/snappymail/v/2.17.3/static/js/min/app.min.js:1
    showMessageComposer https://mail.mydomain.de/snappymail/v/2.17.3/static/js/min/app.min.js:1
    Ds https://mail.mydomain.de/snappymail/v/2.17.3/static/js/min/app.min.js:1
    replyOrforward https://mail.mydomain.de/snappymail/v/2.17.3/static/js/min/app.min.js:1
    t https://mail.mydomain.de/snappymail/v/2.17.3/static/js/min/app.min.js:1
    s https://mail.mydomain.de/snappymail/v/2.17.3/static/js/min/app.min.js:1
    init https://mail.mydomain.de/snappymail/v/2.17.3/static/js/min/libs.min.js:1
    init https://mail.mydomain.de/snappymail/v/2.17.3/static/js/min/libs.min.js:1
    L https://mail.mydomain.de/snappymail/v/2.17.3/static/js/min/libs.min.js:1
    L https://mail.mydomain.de/snappymail/v/2.17.3/static/js/min/libs.min.js:1
    init https://mail.mydomain.de/snappymail/v/2.17.3/static/js/min/libs.min.js:1
    init https://mail.mydomain.de/snappymail/v/2.17.3/static/js/min/libs.min.js:1
    init https://mail.mydomain.de/snappymail/v/2.17.3/static/js/min/app.min.js:1
    a https://mail.mydomain.de/snappymail/v/2.17.3/static/js/min/libs.min.js:1
    N https://mail.mydomain.de/snappymail/v/2.17.3/static/js/min/libs.min.js:1
    a https://mail.mydomain.de/snappymail/v/2.17.3/static/js/min/libs.min.js:1
    a https://mail.mydomain.de/snappymail/v/2.17.3/static/js/min/libs.min.js:1
    n https://mail.mydomain.de/snappymail/v/2.17.3/static/js/min/libs.min.js:1
    t https://mail.mydomain.de/snappymail/v/2.17.3/static/js/min/libs.min.js:1
    n https://mail.mydomain.de/snappymail/v/2.17.3/static/js/min/libs.min.js:1
    t https://mail.mydomain.de/snappymail/v/2.17.3/static/js/min/libs.min.js:1
    n https://mail.mydomain.de/snappymail/v/2.17.3/static/js/min/libs.min.js:1
    t https://mail.mydomain.de/snappymail/v/2.17.3/static/js/min/libs.min.js:1
    n https://mail.mydomain.de/snappymail/v/2.17.3/static/js/min/libs.min.js:1
    t https://mail.mydomain.de/snappymail/v/2.17.3/static/js/min/libs.min.js:1
    n https://mail.mydomain.de/snappymail/v/2.17.3/static/js/min/libs.min.js:1
    t https://mail.mydomain.de/snappymail/v/2.17.3/static/js/min/libs.min.js:1
    n https://mail.mydomain.de/snappymail/v/2.17.3/static/js/min/libs.min.js:1
    t https://mail.mydomain.de/snappymail/v/2.17.3/static/js/min/libs.min.js:1
    n https://mail.mydomain.de/snappymail/v/2.17.3/static/js/min/libs.min.js:1
    t https://mail.mydomain.de/snappymail/v/2.17.3/static/js/min/libs.min.js:1
    n https://mail.mydomain.de/snappymail/v/2.17.3/static/js/min/libs.min.js:1
    t https://mail.mydomain.de/snappymail/v/2.17.3/static/js/min/libs.min.js:1
    vb https://mail.mydomain.de/snappymail/v/2.17.3/static/js/min/libs.min.js:1
    init https://mail.mydomain.de/snappymail/v/2.17.3/static/js/min/libs.min.js:1
    ac https://mail.mydomain.de/snappymail/v/2.17.3/static/js/min/libs.min.js:1
    P https://mail.mydomain.de/snappymail/v/2.17.3/static/js/min/libs.min.js:1
    Cb https://mail.mydomain.de/snappymail/v/2.17.3/static/js/min/libs.min.js:1
    s https://mail.mydomain.de/snappymail/v/2.17.3/static/js/min/libs.min.js:1
    s https://mail.mydomain.de/snappymail/v/2.17.3/static/js/min/libs.min.js:1
    La https://mail.mydomain.de/snappymail/v/2.17.3/static/js/min/libs.min.js:1
    t https://mail.mydomain.de/snappymail/v/2.17.3/static/js/min/libs.min.js:1
    MailMessageList https://mail.mydomain.de/snappymail/v/2.17.3/static/js/min/app.min.js:1
    itemSelected https://mail.mydomain.de/snappymail/v/2.17.3/static/js/min/app.min.js:1
    o https://mail.mydomain.de/snappymail/v/2.17.3/static/js/min/app.min.js:1
    t https://mail.mydomain.de/snappymail/v/2.17.3/static/js/min/libs.min.js:1
    setTimeout handler*Function.prototype.debounce/< https://mail.mydomain.de/snappymail/v/2.17.3/static/js/min/libs.min.js:1
    Selector https://mail.mydomain.de/snappymail/v/2.17.3/static/js/min/app.min.js:1
    s https://mail.mydomain.de/snappymail/v/2.17.3/static/js/min/libs.min.js:1
    s https://mail.mydomain.de/snappymail/v/2.17.3/static/js/min/libs.min.js:1
    La https://mail.mydomain.de/snappymail/v/2.17.3/static/js/min/libs.min.js:1
    t https://mail.mydomain.de/snappymail/v/2.17.3/static/js/min/libs.min.js:1
    selectMessageItem https://mail.mydomain.de/snappymail/v/2.17.3/static/js/min/app.min.js:1
    actionClick https://mail.mydomain.de/snappymail/v/2.17.3/static/js/min/app.min.js:1
    click https://mail.mydomain.de/snappymail/v/2.17.3/static/js/min/app.min.js:1
    y https://mail.mydomain.de/snappymail/v/2.17.3/static/js/min/app.min.js:1
    y https://mail.mydomain.de/snappymail/v/2.17.3/static/js/min/app.min.js:1
    init https://mail.mydomain.de/snappymail/v/2.17.3/static/js/min/app.min.js:1
    onBuild https://mail.mydomain.de/snappymail/v/2.17.3/static/js/min/app.min.js:1
    bi https://mail.mydomain.de/snappymail/v/2.17.3/static/js/min/app.min.js:1
    vi https://mail.mydomain.de/snappymail/v/2.17.3/static/js/min/app.min.js:1
    vi https://mail.mydomain.de/snappymail/v/2.17.3/static/js/min/app.min.js:1
    parse https://mail.mydomain.de/snappymail/v/2.17.3/static/js/min/libs.min.js:1
    l https://mail.mydomain.de/snappymail/v/2.17.3/static/js/min/libs.min.js:1
    l https://mail.mydomain.de/snappymail/v/2.17.3/static/js/min/libs.min.js:1
    init https://mail.mydomain.de/snappymail/v/2.17.3/static/js/min/libs.min.js:1
    Fi https://mail.mydomain.de/snappymail/v/2.17.3/static/js/min/app.min.js:1
    start https://mail.mydomain.de/snappymail/v/2.17.3/static/js/min/app.min.js:1
    ei https://mail.mydomain.de/snappymail/v/2.17.3/static/js/min/app.min.js:1
    promise callback*ei https://mail.mydomain.de/snappymail/v/2.17.3/static/js/min/app.min.js:1
    start https://mail.mydomain.de/snappymail/v/2.17.3/static/js/min/app.min.js:1
    bootstart https://mail.mydomain.de/snappymail/v/2.17.3/static/js/min/app.min.js:1
    bootstart https://mail.mydomain.de/snappymail/v/2.17.3/static/js/min/app.min.js:1
    d https://mail.mydomain.de/#/mailbox/INBOX:56
    initData https://mail.mydomain.de/#/mailbox/INBOX:56
    promise callback*initData https://mail.mydomain.de/#/mailbox/INBOX:56
    <anonymous> https://mail.mydomain.de/?/AppData/0/7904745246220926/:1
app.min.js:1:164954
```

**Comment by codiflow** [comment]
Ok nevermind – got it fixed. There also need to be stuff replaced in the `min` folder...

Haven't seen that.
