### ISSUE TITLE
When trying to upgrade from 2.20.6 to 2.21.0 ?admin refuse

### ISSUE THREAD

**Issue by master3395** [the-djmaze/snappymail#664]
Hello.

When i try to upgrade from 2.20.6 to 2.21.0, I just get refused to log in from ?admin.
If I downgrade to 2.20.6 login works again.
I am running PHP 8.1.10

![image](https://user-images.githubusercontent.com/4199669/201488584-494041e9-6607-414a-9b9a-567ce63c0d2a.png)

**Comment by neildarlow** [comment]
Seeing the same with SnappyMail-2.21.0 and PHP-8.1.12 but also normal user login fails in the same manner.

I'm running Lighttpd and lighttpd-angel reports an inactive/expired X509 certificate for the fullchain.pem certificate which is bogus.

For me, SnappyMail-2.20.6 worked also but a downgrade back to that version from 2.21.0 doesn't restore operation.

**Comment by the-djmaze** [comment]
Yes it should be fixed. The issue is OpenSSL fixes in v2.20 that i couldn't test.

WithSodium installed, it should work.

**Comment by setoy** [comment]
Also getting the same error after upgrading to 2.21.0:

```
[2022-11-13 10:01:53.833][8a863718] [ERROR]: ArgumentCountError: Too few arguments to function SnappyMail\Log::error(), 1 passed in path\to\snappymail\snappymail\v\2.21.0\app\libraries\snappymail\crypt.php on line 102 and exactly 2 expected in path\to\snappymail\snappymail\v\2.21.0\app\libraries\snappymail\log.php:18
Stack trace:
#0 path\to\snappymail\snappymail\v\2.21.0\app\libraries\snappymail\crypt.php(102): SnappyMail\Log::error('Undefined const...')
#1 path\to\snappymail\snappymail\v\2.21.0\app\libraries\snappymail\crypt.php(123): SnappyMail\Crypt::Encrypt('{"email":"*REDACTED*', NULL)
#2 path\to\snappymail\snappymail\v\2.21.0\app\libraries\RainLoop\Actions\UserAuth.php(155): SnappyMail\Crypt::EncryptToJSON(Object(RainLoop\Model\MainAccount))
#3 path\to\snappymail\snappymail\v\2.21.0\app\libraries\RainLoop\Actions\UserAuth.php(303): RainLoop\Actions::SetAccountCookie('smaccount', Object(RainLoop\Model\MainAccount))
#4 path\to\snappymail\snappymail\v\2.21.0\app\libraries\RainLoop\Actions\User.php(49): RainLoop\Actions->SetAuthToken(Object(RainLoop\Model\MainAccount))
#5 path\to\snappymail\snappymail\v\2.21.0\app\libraries\RainLoop\ServiceActions.php(155): RainLoop\Actions->DoLogin()
#6 path\to\snappymail\snappymail\v\2.21.0\app\libraries\RainLoop\Service.php(123): RainLoop\ServiceActions->ServiceJson('')
#7 path\to\snappymail\snappymail\v\2.21.0\app\libraries\RainLoop\Service.php(15): RainLoop\Service::RunResult()
#8 path\to\snappymail\snappymail\v\2.21.0\include.php(167): RainLoop\Service::Handle()
#9 path\to\snappymail\index.php(11): include('path\to\sn...')
#10 {main}
```
