### ISSUE TITLE
Raise JS TypeEroor "toLowerCase" after update to 2.35.3

### ISSUE THREAD

**Issue by MichaelJumble** [the-djmaze/snappymail#1491]
Select Mail Button at Top of Nextcloud 27x+28x  with Link

/index.php/apps/snappymail/

Raise this error at frontpage:

```
An error occurred.
Please refresh the page and try again.TypeError: (F(...) || "").toLowerCase is not a function
A clear and concise description of what the bug is.
```

Happen since update SnappyMail to 2.35.3

**Comment by derStephan** [comment]
Having the same problem in standalone version after update to 2.35.3

```
An error occurred.
Please refresh the page and try again.
TypeError: (intermediate value).toLowerCase is not a function
```

in console it says

`Uncaught (in promise) TypeError: (intermediate value).toLowerCase is not a function`

**Comment by derStephan** [comment]
Wow, your response times are incredible.

**Comment by the-djmaze** [comment]
> Wow, your response times are incredible.

Thanks!
I'm just... https://www.youtube.com/watch?v=LQ6VyqMT5YA
