### ISSUE TITLE
Updgrade to 2.4.0 : Change password doesn't work anymore : blank page

### ISSUE THREAD

**Issue by dominiquefournier** [the-djmaze/snappymail#61]
**Describe the bug**
After upgrading to 2.4.0, the change password page is not displayed anymore

**To Reproduce**
1. Go to 'Parameters/Password change'
2. The URL is changed but the content of the page "Password" is not displayed.
In console : 
```
Uncaught TypeError: ko.addObservablesTo is not a function
    ChangePasswordUserSettings https://mail.xxx/snappymail/?/Plugins/0/User/89c0f1bcafddb02dc37306ab11d302e1/:12
    onRoute https://mail.xxx/snappymail/snappymail/v/2.4.0/static/js/min/app.min.js:1
    parse https://mail.xxx/snappymail/snappymail/v/2.4.0/static/js/min/libs.min.js:1
    Us https://mail.xxx/snappymail/snappymail/v/2.4.0/static/js/min/app.min.js:1
snappymail:12:7
```

**Expected behavior**
Display the form page to allow to change the password

**Desktop (please complete the following information):**
 - Browser firefox 78.8 ESR
 - SnappyMail Version 2.4.0

**Comment by the-djmaze** [comment]
Mij bad!
I missed the plugin while making speed changes.
Will make easy fix for it.

**Comment by dominiquefournier** [comment]
Oops same error with 2.4.1 : 
```
Uncaught TypeError: ko.addObservablesTo is not a function
    ChangePasswordUserSettings https://mail.xxx/snappymail/?/Plugins/0/User/c1079bada42a32074a59e6e07199c8e1/:12
    onRoute https://mail.xxx/snappymail/snappymail/v/2.4.1/static/js/min/app.min.js:1
    parse https://mail.xxx/snappymail/snappymail/v/2.4.1/static/js/min/libs.min.js:1
    Os https://mail.xxx/snappymail/snappymail/v/2.4.1/static/js/min/app.min.js:1
snappymail:12:7

```

**Comment by the-djmaze** [comment]
Can't upgrade the plugin?

https://snappymail.eu/repository/v2/plugins/change-password-2.1.tgz
https://snappymail.eu/repository/v2/plugins/change-password.phar

**Comment by dominiquefournier** [comment]
Well done !
What is the "standard" process to update ? I just explode the tar in the plugin dir, and the the chown. Is there something more ?
Do you want to prepare a plugin update process which will be available in admin part ?

**Comment by the-djmaze** [comment]
Admin has an update feature.
The plugins screen shows installed and updates.
However, the repository json is cached and not always updated.

I will think about a feature to remove cache and update plugins on version change.
