### ISSUE TITLE
Unable to open mail with Avatars plugin/Extension

### ISSUE THREAD

**Issue by DeveloperJoshua14** [the-djmaze/snappymail#1649]
Hello! After Setting up SnappyMail with my CyberPanel install, I got the Admin panel  to do the fine tunning. One thing I wanted was to have Avatars, and that is an extension! Once I had added it, I could no longer open emails. I could login to webMail, and see new emails. If I double middle clicked, it would open in a new tab, but would not open in the side view. After disabling it (Avatars), it was working perfectly. I am new to Snappymail, so I looked through the logs that CyberPanel provided, but there was no issues. 

1. Enable "Avatars"
2. Refresh WebMail
3. Try and open an email

- Browser: Chrome 126.0.6478.127, Chrome Mobile, Microsoft Edge 126.0.2592.81
- IMAP daemon: I _think_ dovecot
- PHP version: Under "PHP optional extensions" in ?admin#/about, it says: PHP 8.0.30
- SnappyMail Version:2.28.1
- Mode: cyberpanel

**Additional context**
This is not the end of the world if it is not going to work (If I broke something). Thank you to everyone who has put in any work to SnappyMail, you guys (And gals) are the ones who are keeping this world together, one bug and line of code at a time <3

**Comment by the-djmaze** [comment]
There could be an issue with a certain configuration of the plugin (as it has many options).

When you enable debug logs there are several places to find info.
It is documented in the wiki how to obtain it.

**Comment by the-djmaze** [comment]
I've tried, but i couldn't reproduce the error.
Did you find it?

**Comment by DeveloperJoshua14** [comment]
Hello! Thank you so much for responding, and I am so sorry I did not respond sooner. Looking at the client side logs, I am getting this:
`?/Plugins/0/User/06a…1aa3b7a81dffa6/:610 Uncaught 
TypeError: msg.headers is not a function
    at getBimiSelector (?/Plugins/0/User/06a…3b7a81dffa6/:610:27)
    at getBimiId (?/Plugins/0/User/06a…3b7a81dffa6/:614:73)
    at getAvatarUid (?/Plugins/0/User/06a…3b7a81dffa6/:616:28)
    at getAvatar (?/Plugins/0/User/06a…3b7a81dffa6/:617:84)
    at ka.pb (?/Plugins/0/User/06a…3b7a81dffa6/:777:32)
    at libs.js:1142:123
    at Set.forEach (<anonymous>)
    at Function.D (libs.js:1142:103)
    at Function.Oa (libs.js:1145:322)
    at Object.b [as message] (libs.js:1145:16)`

As for the server side logs, there is nothing in there that is pointing to an issue. It only logs when: (New email, delete email, archive email, ect. Nothing about this.)

also, this is a screenshot of with and without the avatar extension enabled:
WITH IT ENABLED
![image](https://github.com/the-djmaze/snappymail/assets/85973108/2fc0172f-0a5e-4448-b1d5-27d0a5083624)
WITH IT DISABLED
![image](https://github.com/the-djmaze/snappymail/assets/85973108/7a7307d9-0026-42ef-8fb5-03c94d5f4816)


Thank you

**Comment by the-djmaze** [comment]
Ah you are using SnappyMail 2.28.1

The avatars plugin only works with 2.33+

**Comment by DeveloperJoshua14** [comment]
Oh. Whoops! Thank you, and sorry to make you point out the obvious. Thank you!
